matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd src/processing
        - pip install -r requirements.txt
      script:
        - python -m pylama
        - python -m unittest discover

    - language: node_js
      node_js: 14
      before_script:
        - cd src
        - npm install
      script:
        - npm run eslint