language: node_js
node_js: 14

cache:
  bundler: true
  directories:
  - src/node_modules

jobs:
  include:
    - stage: linting
      install:
        - cd src
        - npm install
        - cd processing
        - pip install -r requirements
      script:
        - cd src
        - npm run eslint
        - cd processing
        - python -m pylama
    - stage: testing
      script:
        - python -m unittest discover