jobs:
  include:
    - language: python
      python: 3.9
      before_script:
        - cd src/processing
        - pip install -r requirements.txt
      script:
        - python -m unittest discover
        - python -m pylama
    - language: node_js
      node_js: 14
      before_script:
        - cd src
        - npm install
      script:
        - npm run eslint