branches:
  only:
    - master

matrix:
  include:
    - language: python
      python: 3.9
      - stage: testing
        before_script:
          - cd src/processing
          - pip install -r requirements.txt
        script:
          - python -m unittest discover
          - python -m pylama
    - language: node_js
      - stage: testing
        before_script:
          - cd src
          - npm install
        script:
          - npm run eslint