matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - pip install pylama==7.7.1
        - cd src/processing/scheduler
        - pip install -r requirements.txt
      script:
        - python -m unittest discover
        - cd ..
        - python -m pylama

    - language: node_js
      node_js: 14
      before_script:
        - cd src/webapp
        - npm install
      script:
        - npm run eslint

    - language: generic
      services: docker
      sudo: required
      script:
        - cd src/processing
        - docker-compose up -d --build
        - docker-compose stop