matrix:
  include:
    - language: python
      python:
      - - "3.8"
      install:
        - cd src/backend
        - pip install -r requirements.txt
      script:
        - cd src/backend
        - python -m unittest discover
        - python -m pylama badpackets

    - language: node_js