FROM python:3.9-alpine

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true

COPY ./scheduler /scheduler
WORKDIR /scheduler

RUN apk update && apk add tzdata
RUN ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
RUN pip install -r requirements.txt

CMD ["python", "-u", "scheduler.py"]